---
- name: Converge
  hosts: all
  roles:
    - role: systemd
      tags:
        - molecule-idempotence-notest

    - role: systemd
      systemd_journald:
        Audit:
        Compress: true
      systemd_logind:
        KillOnlyUsers:
          - vagrant
      systemd_system:
        CrashReboot: false
      systemd_user:
        LogColor: true
        LogTime: false
...
