---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure virtualenv ansible version is gathered
      tags:
        - virtualenv
      ansible.builtin.command:
        cmd: >
          {{ virtualenv_list[0].virtualenv }}/bin/ansible --version
      register: __virtualenv_ansible_version
      changed_when: false

    - name: Ensure virtualenv ansible version is verified
      tags:
        - virtualenv
      ansible.builtin.assert:
        that:
          - __virtualenv_ansible_version.stdout is search('ansible.*core.*2\.18')
...
