---
- name: Ensure rclone config facts are generated
  tags:
    - rclone
  ansible.builtin.set_fact:
    __rclone_profile:
      "{{ rclone_profile |
          combine({'rclone_config': rclone_config_path}) }}"
    __rclone_sysconfig:
      "{{ rclone_sysconfig |
          combine({'rclone_config': rclone_config_path}) }}"

- name: Ensure rclone config pass facts are generated
  tags:
    - rclone
  ansible.builtin.set_fact:
    __rclone_sysconfig:
      "{{ __rclone_sysconfig |
          combine({'rclone_config_pass': rclone_config_pass}) }}"
  when:
    - rclone_config_pass is not none
    - rclone_mounts | length > 0

- name: Ensure rclone packages are present
  tags:
    - rclone
  become: true
  ansible.builtin.dnf:
    name:
      - fuse3
      - fuse3-libs
      - python3-pycryptodomex
      - rclone
    state: present
    validate_certs: true

- name: Ensure rclone configuration path is present
  tags:
    - rclone
  become: true
  ansible.builtin.file:
    group: root
    mode: '0700'
    owner: root
    path: "{{ rclone_config_path | dirname }}"
    state: directory

- name: Ensure rclone configuration file is managed
  tags:
    - rclone
  become: true
  no_log: "{{ rclone_no_log }}"
  linuxhq.linux.rclone_config_encryption:
    content:
      "{{ lookup('ansible.builtin.template', 'rclone.conf.j2') | d('', true) }}"
    group: root
    mode: '0600'
    owner: root
    password: "{{ rclone_config_pass | d(omit) }}"
    path: "{{ rclone_config_path }}"
    state: "{{ 'present' if rclone_config_pass is not none else 'absent' }}"

- name: Ensure rclone profile configuration is managed
  tags:
    - rclone
  become: true
  ansible.builtin.template:
    group: root
    dest: /etc/profile.d/rclone.sh
    mode: '0644'
    owner: root
    src: rclone.profile.j2

- name: Ensure rclone sysconfig configuration is managed
  tags:
    - rclone
  become: true
  ansible.builtin.template:
    group: root
    dest: /etc/sysconfig/rclone
    mode: '0600'
    owner: root
    src: rclone.sysconfig.j2

- name: Ensure rclone systemd unit is managed
  tags:
    - rclone
  become: true
  ansible.builtin.template:
    group: root
    dest: /usr/lib/systemd/system/{{ _mount.name }}.service
    mode: '0644'
    owner: root
    src: rclone.systemd.j2
  loop: "{{ rclone_mounts }}"
  loop_control:
    label: "{{ _mount.name | d(none) }}"
    loop_var: _mount
  when:
    - _mount.name is defined
    - _mount.mountpoint is defined
    - _mount.remote is defined

- name: Ensure rclone systemd unit is reloaded
  tags:
    - rclone
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  when:
    - rclone_mounts | length > 0

- name: Ensure rclone systemd units are started and enabled on boot
  tags:
    - rclone
  become: true
  ansible.builtin.systemd_service:
    enabled: true
    name: "{{ _mount.name }}.service"
    state: started
  loop: "{{ rclone_mounts }}"
  loop_control:
    label: "{{ _mount.name | d(none) }}"
    loop_var: _mount
  when:
    - _mount.name is defined
    - _mount.mountpoint is defined
    - _mount.remote is defined
...
