---
- name: Ensure kopia repository key is present
  tags:
    - kopia
  become: true
  ansible.builtin.rpm_key:
    key: https://kopia.io/signing-key
    state: present

- name: Ensure kopia repository file is present
  tags:
    - kopia
  become: true
  ansible.builtin.yum_repository:
    baseurl: http://packages.kopia.io/rpm/stable/$basearch/
    description: Kopia
    enabled: true
    gpgcheck: true
    gpgkey: https://kopia.io/signing-key
    file: kopia
    name: Kopia

- name: Ensure kopia packages are present
  tags:
    - kopia
  become: true
  ansible.builtin.dnf:
    name: "{{ kopia_packages }}"
    state: present

- name: Ensure kopia repository path is present
  tags:
    - kopia
  become: true
  ansible.builtin.file:
    group: root
    mode: '0700'
    owner: root
    path: "{{ kopia_repository.options.path }}"
    state: directory
  when:
    - kopia_repository.storage | d(none) == 'filesystem'
    - kopia_repository.options.path is defined

- name: Ensure kopia repository is managed
  tags:
    - kopia
  become: true
  linuxhq.linux.kopia_repository:
    options: "{{ kopia_repository.options | d(omit) }}"
    password: "{{ kopia_password }}"
    secrets: "{{ kopia_repository.secrets | d(omit) }}"
    storage: "{{ kopia_repository.storage }}"
    validate_provider: "{{ kopia_repository.validate_provider | d(false) }}"
  when:
    - kopia_repository | length > 0

- name: Ensure kopia maintenance settings are managed
  tags:
    - kopia
  become: true
  linuxhq.linux.kopia_maintenance:
    enable_full: "{{ kopia_maintenance.enable_full | d(omit) }}"
    enable_quick: "{{ kopia_maintenance.enable_quick | d(omit) }}"
    extend_object_locks: "{{ kopia_maintenance.extend_object_locks | d(omit) }}"
    full_interval: "{{ kopia_maintenance.full_interval | d(omit) }}"
    list_parallelism: "{{ kopia_maintenance.list_parallelism | d(omit) }}"
    max_retained_log_age: "{{ kopia_maintenance.max_retained_log_age | d(omit) }}"
    max_retained_log_count:
      "{{ kopia_maintenance.max_retained_log_count | d(omit) }}"
    max_retained_log_size_mb:
      "{{ kopia_maintenance.max_retained_log_size_mb | d(omit) }}"
    owner: "{{ kopia_maintenance.owner | d(omit) }}"
    quick_interval: "{{ kopia_maintenance.quick_interval | d(omit) }}"
  when:
    - kopia_maintenance | length > 0

- name: Ensure kopia policies are managed
  tags:
    - kopia
  become: true
  linuxhq.linux.kopia_policy:
    policy: "{{ _policy.policy | d(omit) }}"
    state: "{{ _policy.state | d('present') }}"
    target: "{{ _policy.target }}"
  loop: "{{ kopia_policies }}"
  loop_control:
    label: "{{ _policy.target | d(none) }}"
    loop_var: _policy
  when:
    - _policy.target is defined

- name: Ensure kopia snapshots are present
  tags:
    - kopia
  become: true
  linuxhq.linux.kopia_snapshot:
    password: "{{ kopia_password }}"
    path: "{{ _snapshot.target }}"
  loop: "{{ kopia_policies }}"
  loop_control:
    label: "{{ _snapshot.target | d(none) }}"
    loop_var: _snapshot
  when:
    - kopia_snapshot | bool
    - _snapshot.target is defined

- name: Ensure kopia systemd configuration is managed
  tags:
    - kopia
  become: true
  ansible.builtin.template:
    dest: /usr/lib/systemd/system/kopia.service
    group: root
    mode: '0644'
    owner: root
    src: kopia.systemd.j2
  notify:
    - Restart kopia

- name: Ensure kopia systemd is reloaded
  tags:
    - kopia
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Ensure kopia is started and enabled on boot
  tags:
    - kopia
  become: true
  ansible.builtin.service:
    enabled: true
    name: kopia.service
    state: started
...
