---
- name: Verify
  hosts: all
  roles:
    - kopia_repository_info

  post_tasks:
    - name: Ensure kopia information is verified
      tags:
        - kopia_repository_info
      ansible.builtin.assert:
        that:
          - _kopia_repository_info_dict.storage.type == kopia_repository.storage
          - _kopia_repository_info_dict.storage.config.path ==
            kopia_repository.options.path

    - name: Ensure kopia information is displayed
      tags:
        - kopia_repository_info
      ansible.builtin.debug:
        msg: |
          {{ _kopia_repository_info_dict | to_nice_yaml }}
...
