---
- name: Converge
  hosts: all
  roles:
    - role: kopia
      kopia_maintenance: {}
      kopia_policies: []
      kopia_repository: {}
      tags:
        - molecule-idempotence-notest

    - kopia
...
