---
- name: Converge
  hosts: all
  roles:
    - role: rclone
      rclone_config: []
      rclone_config_pass: null
      rclone_mounts: []
      rclone_profile: {}
      rclone_sysconfig: {}
      tags:
        - molecule-idempotence-notest

    - rclone
...
