---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure rush stat information is gathered
      tags:
        - rush
      ansible.builtin.stat:
        path: /usr/sbin/rush
      register: __rush_stat

    - name: Ensure rush stat information is verified
      tags:
        - rush
      ansible.builtin.assert:
        that:
          - __rush_stat.stat.exists | bool
...
